Header header               # Header.
uint32 id                   # Id of the obstacle.
string type                 # Type of the obstacle (positive, negative, supended).
geometry_msgs/Pose pose     # Approximate pose of the obstacle (only position).
float64 width               # Width of the obstacle.
float64 length              # Length of the obstacle.
float64 height              # Height of the obstacle.
