# Requested submap position in x-direction [m].
float32 positionX
  
# Requested submap position in y-direction [m].
float32 positionY

# Requested submap length in x-direction [m].
float32 lengthInX
  
# Requested submap width in y-direction [m].
float32 lengthInY

# Optionally, get color data.
bool computeColor

# Optionally, get the surface normals.
bool computeSurfaceNormal

---

# Submap
elevation_map_msg/ElevationMap elevation_map